import { collection, addDoc, serverTimestamp, getDocs, query, where } from 'firebase/firestore';
import { db } from './firebase';

const storeProducts = [
  {
    name: 'Arduino Uno R3 Board',
    description: 'لوحة تطوير Arduino الأساسية مع معالج ATmega328P، مثالية لمشاريع الإلكترونيات والروبوتات التعليمية',
    price: 85,
    originalPrice: 95,
    category: 'electronics',
    features: ['معالج ATmega328P', '14 منفذ رقمي', '6 مدخلات تناظرية', 'واجهة USB للبرمجة'],
    tags: ['arduino', 'microcontroller', 'programming', 'electronics'],
    image: 'https://images.pexels.com/photos/2599244/pexels-photo-2599244.jpeg?auto=compress&cs=tinysrgb&w=400',
    rating: 4.8,
    reviews: 156,
    inStock: true,
    stockQuantity: 50,
    discount: 10,
    featured: true
  },
  {
    name: 'Raspberry Pi 4 Model B',
    description: 'حاسوب صغير بحجم بطاقة الائتمان مع معالج رباعي النواة، مثالي لمشاريع البرمجة والذكاء الاصطناعي',
    price: 320,
    originalPrice: 350,
    category: 'electronics',
    features: ['معالج رباعي النواة 1.5GHz', '4GB RAM', 'WiFi و Bluetooth', 'منافذ USB 3.0'],
    tags: ['raspberry-pi', 'computer', 'programming', 'ai'],
    image: 'https://images.pexels.com/photos/2582937/pexels-photo-2582937.jpeg?auto=compress&cs=tinysrgb&w=400',
    rating: 4.9,
    reviews: 203,
    inStock: true,
    stockQuantity: 25,
    discount: 8,
    featured: true
  },
  {
    name: 'Breadboard Kit',
    description: 'مجموعة لوحات التجارب للنماذج الأولية، تشمل لوحات بأحجام مختلفة وأسلاك توصيل',
    price: 45,
    category: 'electronics',
    features: ['3 لوحات بأحجام مختلفة', '65 سلك توصيل', 'نقاط ربط 830', 'قاعدة مطاطية مانعة للانزلاق'],
    tags: ['breadboard', 'prototyping', 'electronics', 'wiring'],
    image: 'https://images.pexels.com/photos/163100/circuit-circuit-board-resistor-computer-163100.jpeg?auto=compress&cs=tinysrgb&w=400',
    rating: 4.6,
    reviews: 89,
    inStock: true,
    stockQuantity: 75,
    featured: false
  },
  {
    name: 'LED Assortment Pack',
    description: 'مجموعة متنوعة من مصابيح LED بألوان وأحجام مختلفة لمشاريع الإضاءة والإشارات',
    price: 25,
    category: 'electronics',
    features: ['200 قطعة LED', '5 ألوان مختلفة', 'أحجام 3mm و 5mm', 'مقاومات مدمجة'],
    tags: ['led', 'lights', 'electronics', 'indicators'],
    image: 'https://images.pexels.com/photos/442150/pexels-photo-442150.jpeg?auto=compress&cs=tinysrgb&w=400',
    rating: 4.4,
    reviews: 67,
    inStock: true,
    stockQuantity: 100,
    featured: false
  },
  {
    name: 'Resistor Kit',
    description: 'مجموعة شاملة من المقاومات بقيم مختلفة، منظمة في صندوق تخزين مع ملصقات',
    price: 35,
    category: 'electronics',
    features: ['600 مقاومة', '30 قيمة مختلفة', 'دقة 1%', 'صندوق تنظيم مع ملصقات'],
    tags: ['resistors', 'electronics', 'components', 'passive'],
    image: 'https://images.pexels.com/photos/163100/circuit-circuit-board-resistor-computer-163100.jpeg?auto=compress&cs=tinysrgb&w=400',
    rating: 4.5,
    reviews: 78,
    inStock: true,
    stockQuantity: 80,
    featured: false
  },
  {
    name: 'Capacitor Assortment',
    description: 'مجموعة متنوعة من المكثفات الكهربائية والسيراميكية لدوائر التصفية والتخزين',
    price: 40,
    category: 'electronics',
    features: ['120 مكثف', 'أنواع مختلفة', 'قيم من 1pF إلى 1000µF', 'جهود متنوعة'],
    tags: ['capacitors', 'electronics', 'components', 'filtering'],
    image: 'https://images.pexels.com/photos/163100/circuit-circuit-board-resistor-computer-163100.jpeg?auto=compress&cs=tinysrgb&w=400',
    rating: 4.3,
    reviews: 54,
    inStock: true,
    stockQuantity: 60,
    featured: false
  },
  {
    name: 'Micro Servo Motor',
    description: 'محرك سيرفو صغير عالي الدقة للتحكم في الحركة الدورانية في مشاريع الروبوتات',
    price: 55,
    category: 'electronics',
    features: ['عزم دوران 1.8 كجم/سم', 'زاوية دوران 180°', 'تحكم PWM', 'خفيف الوزن 9 جرام'],
    tags: ['servo', 'motor', 'robotics', 'control'],
    image: 'https://images.pexels.com/photos/2582937/pexels-photo-2582937.jpeg?auto=compress&cs=tinysrgb&w=400',
    rating: 4.7,
    reviews: 92,
    inStock: true,
    stockQuantity: 45,
    featured: false
  },
  {
    name: 'DC Motor Kit',
    description: 'مجموعة محركات التيار المستمر بسرعات وقوى مختلفة مع عجلات وأقراص تروس',
    price: 75,
    category: 'electronics',
    features: ['4 محركات مختلفة', 'عجلات وتروس', 'سرعات متنوعة', 'جهد تشغيل 3-12V'],
    tags: ['dc-motor', 'motors', 'robotics', 'movement'],
    image: 'https://images.pexels.com/photos/2599244/pexels-photo-2599244.jpeg?auto=compress&cs=tinysrgb&w=400',
    rating: 4.6,
    reviews: 73,
    inStock: true,
    stockQuantity: 35,
    featured: false
  },
  {
    name: 'Ultrasonic Distance Sensor',
    description: 'مستشعر المسافة بالموجات فوق الصوتية لقياس المسافات في مشاريع الروبوتات والأتمتة',
    price: 30,
    category: 'electronics',
    features: ['مدى قياس 2-400 سم', 'دقة 3 مم', 'زاوية قياس 15°', 'واجهة رقمية سهلة'],
    tags: ['ultrasonic', 'sensor', 'distance', 'robotics'],
    image: 'https://images.pexels.com/photos/442150/pexels-photo-442150.jpeg?auto=compress&cs=tinysrgb&w=400',
    rating: 4.5,
    reviews: 86,
    inStock: true,
    stockQuantity: 70,
    featured: false
  },
  {
    name: 'Jumper Wire Kit',
    description: 'مجموعة شاملة من أسلاك التوصيل بأطوال وألوان مختلفة للنماذج الأولية',
    price: 20,
    category: 'electronics',
    features: ['120 سلك توصيل', 'أطوال مختلفة', 'ألوان متنوعة', 'نهايات ذكر وأنثى'],
    tags: ['jumper-wires', 'wiring', 'prototyping', 'connections'],
    image: 'https://images.pexels.com/photos/163100/circuit-circuit-board-resistor-computer-163100.jpeg?auto=compress&cs=tinysrgb&w=400',
    rating: 4.4,
    reviews: 95,
    inStock: true,
    stockQuantity: 120,
    featured: false
  },
  {
    name: 'Transistor Assortment',
    description: 'مجموعة متنوعة من الترانزستورات للتحكم في التيار والتضخيم في الدوائر الإلكترونية',
    price: 45,
    category: 'electronics',
    features: ['50 ترانزستور', 'أنواع NPN و PNP', 'قدرات مختلفة', 'دليل مرجعي مرفق'],
    tags: ['transistors', 'electronics', 'amplification', 'switching'],
    image: 'https://images.pexels.com/photos/163100/circuit-circuit-board-resistor-computer-163100.jpeg?auto=compress&cs=tinysrgb&w=400',
    rating: 4.3,
    reviews: 61,
    inStock: true,
    stockQuantity: 55,
    featured: false
  },
  {
    name: 'ESP32 Development Board',
    description: 'لوحة تطوير ESP32 مع WiFi و Bluetooth مدمجين، مثالية لمشاريع إنترنت الأشياء',
    price: 95,
    category: 'electronics',
    features: ['WiFi و Bluetooth مدمجين', 'معالج ثنائي النواة', '30 منفذ GPIO', 'ذاكرة فلاش 4MB'],
    tags: ['esp32', 'wifi', 'bluetooth', 'iot'],
    image: 'https://images.pexels.com/photos/2582937/pexels-photo-2582937.jpeg?auto=compress&cs=tinysrgb&w=400',
    rating: 4.8,
    reviews: 134,
    inStock: true,
    stockQuantity: 40,
    featured: true
  },
  {
    name: 'OLED Display Module',
    description: 'شاشة OLED صغيرة عالية الوضوح لعرض المعلومات في مشاريع الإلكترونيات',
    price: 65,
    category: 'electronics',
    features: ['دقة 128x64 بكسل', 'واجهة I2C', 'استهلاك طاقة منخفض', 'وضوح عالي'],
    tags: ['oled', 'display', 'screen', 'interface'],
    image: 'https://images.pexels.com/photos/442150/pexels-photo-442150.jpeg?auto=compress&cs=tinysrgb&w=400',
    rating: 4.6,
    reviews: 87,
    inStock: true,
    stockQuantity: 30,
    featured: false
  },
  {
    name: 'Stepper Motor with Driver',
    description: 'محرك خطوي عالي الدقة مع دائرة تحكم للحركة الدقيقة في مشاريع الأتمتة',
    price: 120,
    category: 'electronics',
    features: ['دقة 1.8° لكل خطوة', 'عزم دوران عالي', 'دائرة تحكم مدمجة', 'تحكم دقيق في الموضع'],
    tags: ['stepper-motor', 'precision', 'automation', 'control'],
    image: 'https://images.pexels.com/photos/2599244/pexels-photo-2599244.jpeg?auto=compress&cs=tinysrgb&w=400',
    rating: 4.7,
    reviews: 76,
    inStock: true,
    stockQuantity: 20,
    featured: false
  },
  {
    name: 'Relay Module',
    description: 'وحدة ريلاي للتحكم في الأحمال عالية الجهد باستخدام إشارات منخفضة الجهد',
    price: 35,
    category: 'electronics',
    features: ['4 قنوات ريلاي', 'عزل بصري', 'مؤشرات LED', 'تحكم 5V'],
    tags: ['relay', 'switching', 'control', 'isolation'],
    image: 'https://images.pexels.com/photos/163100/circuit-circuit-board-resistor-computer-163100.jpeg?auto=compress&cs=tinysrgb&w=400',
    rating: 4.4,
    reviews: 69,
    inStock: true,
    stockQuantity: 65,
    featured: false
  },
  {
    name: 'Digital Multimeter',
    description: 'جهاز قياس رقمي متعدد الوظائف لقياس الجهد والتيار والمقاومة في الدوائر الإلكترونية',
    price: 180,
    category: 'tools',
    features: ['شاشة LCD كبيرة', 'قياس AC/DC', 'اختبار الاستمرارية', 'حماية من الحمل الزائد'],
    tags: ['multimeter', 'measurement', 'testing', 'electronics'],
    image: 'https://images.pexels.com/photos/6044198/pexels-photo-6044198.jpeg?auto=compress&cs=tinysrgb&w=400',
    rating: 4.7,
    reviews: 112,
    inStock: true,
    stockQuantity: 25,
    featured: true
  },
  {
    name: 'Soldering Iron Kit',
    description: 'مجموعة كاملة للحام الإلكتروني تشمل كاوي لحام قابل للتعديل وملحقات',
    price: 150,
    originalPrice: 180,
    category: 'tools',
    features: ['كاوي لحام 60W', 'درجة حرارة قابلة للتعديل', 'حامل كاوي', '5 رؤوس مختلفة'],
    tags: ['soldering', 'iron', 'electronics', 'tools'],
    image: 'https://images.pexels.com/photos/6044198/pexels-photo-6044198.jpeg?auto=compress&cs=tinysrgb&w=400',
    rating: 4.6,
    reviews: 98,
    inStock: true,
    stockQuantity: 30,
    discount: 16,
    featured: false
  },
  {
    name: 'Precision Screwdriver Set',
    description: 'مجموعة مفكات دقيقة للإلكترونيات والأجهزة الصغيرة بأنواع وأحجام مختلفة',
    price: 65,
    category: 'tools',
    features: ['24 قطعة مختلفة', 'مقابض مغناطيسية', 'صندوق تخزين', 'فولاذ عالي الجودة'],
    tags: ['screwdriver', 'precision', 'tools', 'electronics'],
    image: 'https://images.pexels.com/photos/6044198/pexels-photo-6044198.jpeg?auto=compress&cs=tinysrgb&w=400',
    rating: 4.5,
    reviews: 87,
    inStock: true,
    stockQuantity: 45,
    featured: false
  },
  {
    name: 'Wire Stripper and Cutter',
    description: 'أداة متعددة الوظائف لتعرية وقطع الأسلاك بأحجام مختلفة',
    price: 55,
    category: 'tools',
    features: ['تعرية أسلاك 10-24 AWG', 'قاطع أسلاك مدمج', 'مقبض مريح', 'فولاذ مقاوم للصدأ'],
    tags: ['wire-stripper', 'cutter', 'tools', 'wiring'],
    image: 'https://images.pexels.com/photos/6044198/pexels-photo-6044198.jpeg?auto=compress&cs=tinysrgb&w=400',
    rating: 4.4,
    reviews: 76,
    inStock: true,
    stockQuantity: 50,
    featured: false
  },
  {
    name: 'Heat Shrink Tubing Kit',
    description: 'مجموعة متنوعة من أنابيب الحرارة للعزل وحماية الوصلات الكهربائية',
    price: 30,
    category: 'materials',
    features: ['5 أحجام مختلفة', '5 ألوان', '100 قطعة', 'نسبة انكماش 2:1'],
    tags: ['heat-shrink', 'insulation', 'wiring', 'protection'],
    image: 'https://images.pexels.com/photos/6044198/pexels-photo-6044198.jpeg?auto=compress&cs=tinysrgb&w=400',
    rating: 4.3,
    reviews: 65,
    inStock: true,
    stockQuantity: 80,
    featured: false
  },
  {
    name: 'Solder Wire',
    description: 'سلك لحام إلكتروني عالي الجودة مع نسبة قصدير/رصاص 60/40 وقلب من الراتنج',
    price: 25,
    category: 'materials',
    features: ['وزن 100 جرام', 'قطر 0.8 مم', 'قلب راتنج', 'انصهار سريع'],
    tags: ['solder', 'wire', 'electronics', 'soldering'],
    image: 'https://images.pexels.com/photos/6044198/pexels-photo-6044198.jpeg?auto=compress&cs=tinysrgb&w=400',
    rating: 4.5,
    reviews: 82,
    inStock: true,
    stockQuantity: 90,
    featured: false
  },
  {
    name: 'Copper Tape',
    description: 'شريط نحاسي موصل للكهرباء للدوائر الورقية ومشاريع الإلكترونيات المرنة',
    price: 35,
    category: 'materials',
    features: ['عرض 5 مم', 'طول 30 متر', 'لاصق موصل', 'سمك 0.05 مم'],
    tags: ['copper', 'tape', 'conductive', 'circuits'],
    image: 'https://images.pexels.com/photos/6044198/pexels-photo-6044198.jpeg?auto=compress&cs=tinysrgb&w=400',
    rating: 4.2,
    reviews: 58,
    inStock: true,
    stockQuantity: 70,
    featured: false
  },
  {
    name: 'Thermal Paste',
    description: 'معجون حراري عالي الأداء لنقل الحرارة بين المعالجات والمبردات',
    price: 40,
    category: 'materials',
    features: ['توصيل حراري 8.5 W/mK', 'غير موصل كهربائياً', 'سهل التطبيق', 'حجم 5 جرام'],
    tags: ['thermal', 'paste', 'cooling', 'heatsink'],
    image: 'https://images.pexels.com/photos/6044198/pexels-photo-6044198.jpeg?auto=compress&cs=tinysrgb&w=400',
    rating: 4.6,
    reviews: 74,
    inStock: true,
    stockQuantity: 60,
    featured: false
  },
  {
    name: 'Heatsink Assortment',
    description: 'مجموعة متنوعة من المبردات المعدنية بأحجام مختلفة لتبريد المكونات الإلكترونية',
    price: 50,
    category: 'materials',
    features: ['10 أحجام مختلفة', 'ألومنيوم عالي الجودة', 'تصميم زعانف فعال', 'شريط حراري مرفق'],
    tags: ['heatsink', 'cooling', 'electronics', 'thermal'],
    image: 'https://images.pexels.com/photos/6044198/pexels-photo-6044198.jpeg?auto=compress&cs=tinysrgb&w=400',
    rating: 4.4,
    reviews: 63,
    inStock: true,
    stockQuantity: 40,
    featured: false
  },
  {
    name: 'Acrylic Project Case',
    description: 'صندوق أكريليك شفاف لحماية وعرض المشاريع الإلكترونية',
    price: 60,
    category: 'materials',
    features: ['أكريليك شفاف', 'سهل التجميع', 'فتحات تهوية', 'أبعاد 15×10×5 سم'],
    tags: ['case', 'enclosure', 'acrylic', 'project'],
    image: 'https://images.pexels.com/photos/6044198/pexels-photo-6044198.jpeg?auto=compress&cs=tinysrgb&w=400',
    rating: 4.5,
    reviews: 79,
    inStock: true,
    stockQuantity: 35,
    featured: false
  },
  {
    name: 'Prototyping PCB Board',
    description: 'لوحة دوائر مطبوعة للنماذج الأولية مع نقاط لحام ومناطق توصيل',
    price: 30,
    category: 'materials',
    features: ['مقاس 10×10 سم', 'طبقة نحاسية مزدوجة', 'ثقوب مطلية', 'مناطق توصيل منظمة'],
    tags: ['pcb', 'prototyping', 'electronics', 'circuit'],
    image: 'https://images.pexels.com/photos/163100/circuit-circuit-board-resistor-computer-163100.jpeg?auto=compress&cs=tinysrgb&w=400',
    rating: 4.3,
    reviews: 68,
    inStock: true,
    stockQuantity: 75,
    featured: false
  },
  {
    name: 'Lithium Polymer Battery',
    description: 'بطارية ليثيوم بوليمر قابلة للشحن لتزويد المشاريع المحمولة بالطاقة',
    price: 70,
    category: 'electronics',
    features: ['3.7V 2000mAh', 'خفيفة الوزن', 'حماية مدمجة', 'معدل تفريغ عالي'],
    tags: ['battery', 'lipo', 'power', 'rechargeable'],
    image: 'https://images.pexels.com/photos/6044198/pexels-photo-6044198.jpeg?auto=compress&cs=tinysrgb&w=400',
    rating: 4.5,
    reviews: 91,
    inStock: true,
    stockQuantity: 40,
    featured: false
  },
  {
    name: 'Battery Charger Module',
    description: 'وحدة شحن بطاريات الليثيوم مع حماية من الشحن الزائد والتفريغ العميق',
    price: 45,
    category: 'electronics',
    features: ['شحن بطاريات 3.7V', 'حماية متكاملة', 'مؤشر LED للشحن', 'واجهة USB'],
    tags: ['charger', 'battery', 'lipo', 'protection'],
    image: 'https://images.pexels.com/photos/6044198/pexels-photo-6044198.jpeg?auto=compress&cs=tinysrgb&w=400',
    rating: 4.4,
    reviews: 72,
    inStock: true,
    stockQuantity: 55,
    featured: false
  },
  {
    name: 'Voltage Regulator Modules',
    description: 'وحدات تنظيم الجهد لتوفير جهد ثابت للدوائر الإلكترونية',
    price: 40,
    category: 'electronics',
    features: ['مجموعة من 5 وحدات', 'جهود مختلفة 3.3V/5V/9V/12V', 'تيار حتى 3A', 'حماية من الحرارة'],
    tags: ['voltage', 'regulator', 'power', 'electronics'],
    image: 'https://images.pexels.com/photos/163100/circuit-circuit-board-resistor-computer-163100.jpeg?auto=compress&cs=tinysrgb&w=400',
    rating: 4.3,
    reviews: 64,
    inStock: true,
    stockQuantity: 60,
    featured: false
  },
  {
    name: 'Digital Oscilloscope',
    description: 'جهاز راسم ذبذبات رقمي لعرض وتحليل الإشارات الكهربائية في الدوائر الإلكترونية',
    price: 850,
    originalPrice: 950,
    category: 'tools',
    features: ['نطاق تردد 100MHz', 'معدل عينات 1GS/s', 'شاشة ملونة 7 بوصة', 'واجهة USB'],
    tags: ['oscilloscope', 'measurement', 'signal', 'analysis'],
    image: 'https://images.pexels.com/photos/6044198/pexels-photo-6044198.jpeg?auto=compress&cs=tinysrgb&w=400',
    rating: 4.8,
    reviews: 56,
    inStock: true,
    stockQuantity: 10,
    discount: 10,
    featured: true
  },
  {
    name: 'Logic Analyzer',
    description: 'محلل منطقي لفحص وتصحيح الإشارات الرقمية في الدوائر المنطقية',
    price: 320,
    category: 'tools',
    features: ['8 قنوات', 'معدل عينات 24MHz', 'واجهة USB', 'برمجيات تحليل متقدمة'],
    tags: ['logic', 'analyzer', 'digital', 'debugging'],
    image: 'https://images.pexels.com/photos/6044198/pexels-photo-6044198.jpeg?auto=compress&cs=tinysrgb&w=400',
    rating: 4.6,
    reviews: 48,
    inStock: true,
    stockQuantity: 15,
    featured: false
  },
  {
    name: 'Magnifying Desk Lamp',
    description: 'مصباح مكتبي مع عدسة مكبرة للأعمال الدقيقة في الإلكترونيات واللحام',
    price: 120,
    category: 'tools',
    features: ['عدسة 5X', 'إضاءة LED', 'ذراع قابل للتعديل', 'مشبك تثبيت'],
    tags: ['magnifier', 'lamp', 'soldering', 'precision'],
    image: 'https://images.pexels.com/photos/6044198/pexels-photo-6044198.jpeg?auto=compress&cs=tinysrgb&w=400',
    rating: 4.5,
    reviews: 73,
    inStock: true,
    stockQuantity: 25,
    featured: false
  },
  {
    name: 'Bench Power Supply',
    description: 'مزود طاقة مخبري قابل للتعديل لتغذية الدوائر الإلكترونية بجهود وتيارات مختلفة',
    price: 450,
    originalPrice: 500,
    category: 'tools',
    features: ['جهد قابل للتعديل 0-30V', 'تيار قابل للتعديل 0-5A', 'شاشة رقمية', 'حماية من الحمل الزائد'],
    tags: ['power-supply', 'bench', 'variable', 'electronics'],
    image: 'https://images.pexels.com/photos/6044198/pexels-photo-6044198.jpeg?auto=compress&cs=tinysrgb&w=400',
    rating: 4.7,
    reviews: 62,
    inStock: true,
    stockQuantity: 12,
    discount: 10,
    featured: true
  },
  {
    name: 'Digital Caliper',
    description: 'فرجار رقمي لقياس الأبعاد بدقة عالية في مشاريع الهندسة والتصنيع',
    price: 110,
    category: 'tools',
    features: ['دقة 0.01 مم', 'قياس داخلي وخارجي', 'شاشة LCD', 'تحويل مم/بوصة'],
    tags: ['caliper', 'measurement', 'precision', 'engineering'],
    image: 'https://images.pexels.com/photos/6044198/pexels-photo-6044198.jpeg?auto=compress&cs=tinysrgb&w=400',
    rating: 4.6,
    reviews: 85,
    inStock: true,
    stockQuantity: 30,
    featured: false
  },
  {
    name: 'Helping Hands Soldering Tool',
    description: 'أداة مساعدة للحام مع مشابك قابلة للتعديل وعدسة مكبرة',
    price: 75,
    category: 'tools',
    features: ['مشابك معدنية قابلة للتعديل', 'عدسة مكبرة 2.5X', 'قاعدة ثقيلة مستقرة', 'إسفنجة تنظيف مدمجة'],
    tags: ['soldering', 'helping-hands', 'magnifier', 'tools'],
    image: 'https://images.pexels.com/photos/6044198/pexels-photo-6044198.jpeg?auto=compress&cs=tinysrgb&w=400',
    rating: 4.4,
    reviews: 79,
    inStock: true,
    stockQuantity: 40,
    featured: false
  },
  {
    name: 'Microphone Module',
    description: 'وحدة ميكروفون حساسة للصوت لمشاريع التحكم الصوتي والتعرف على الأصوات',
    price: 25,
    category: 'electronics',
    features: ['حساسية عالية', 'مضخم مدمج', 'إخراج تناظري ورقمي', 'جهد تشغيل 3.3-5V'],
    tags: ['microphone', 'sound', 'sensor', 'audio'],
    image: 'https://images.pexels.com/photos/163100/circuit-circuit-board-resistor-computer-163100.jpeg?auto=compress&cs=tinysrgb&w=400',
    rating: 4.3,
    reviews: 67,
    inStock: true,
    stockQuantity: 65,
    featured: false
  },
  {
    name: 'Temperature Sensor Pack',
    description: 'مجموعة من مستشعرات درجة الحرارة المختلفة لمشاريع المراقبة والتحكم',
    price: 55,
    category: 'electronics',
    features: ['5 أنواع مختلفة', 'نطاق قياس -55 إلى 125°C', 'دقة عالية', 'واجهات رقمية وتناظرية'],
    tags: ['temperature', 'sensor', 'monitoring', 'control'],
    image: 'https://images.pexels.com/photos/163100/circuit-circuit-board-resistor-computer-163100.jpeg?auto=compress&cs=tinysrgb&w=400',
    rating: 4.5,
    reviews: 72,
    inStock: true,
    stockQuantity: 50,
    featured: false
  },
  {
    name: 'Accelerometer Module',
    description: 'وحدة قياس التسارع ثلاثية المحاور لمشاريع الحركة والاستشعار',
    price: 45,
    category: 'electronics',
    features: ['قياس ثلاثي المحاور', 'دقة عالية', 'واجهة I2C', 'جهد تشغيل 3.3-5V'],
    tags: ['accelerometer', 'motion', 'sensor', 'orientation'],
    image: 'https://images.pexels.com/photos/163100/circuit-circuit-board-resistor-computer-163100.jpeg?auto=compress&cs=tinysrgb&w=400',
    rating: 4.4,
    reviews: 68,
    inStock: true,
    stockQuantity: 45,
    featured: false
  },
  {
    name: 'GPS Module',
    description: 'وحدة نظام تحديد المواقع العالمي لمشاريع التتبع والملاحة',
    price: 85,
    category: 'electronics',
    features: ['دقة 2.5 متر', 'هوائي مدمج', 'معدل تحديث 5Hz', 'واجهة UART'],
    tags: ['gps', 'navigation', 'tracking', 'location'],
    image: 'https://images.pexels.com/photos/163100/circuit-circuit-board-resistor-computer-163100.jpeg?auto=compress&cs=tinysrgb&w=400',
    rating: 4.6,
    reviews: 81,
    inStock: true,
    stockQuantity: 30,
    featured: false
  },
  {
    name: 'Bluetooth Module',
    description: 'وحدة اتصال بلوتوث للتواصل اللاسلكي بين الأجهزة والمشاريع',
    price: 40,
    category: 'electronics',
    features: ['بلوتوث 5.0', 'مدى 10 متر', 'واجهة UART', 'جهد تشغيل 3.3V'],
    tags: ['bluetooth', 'wireless', 'communication', 'connectivity'],
    image: 'https://images.pexels.com/photos/163100/circuit-circuit-board-resistor-computer-163100.jpeg?auto=compress&cs=tinysrgb&w=400',
    rating: 4.5,
    reviews: 74,
    inStock: true,
    stockQuantity: 55,
    featured: false
  },
  {
    name: 'Robotics Chassis Kit',
    description: 'هيكل روبوت متكامل مع عجلات ومحركات لبناء روبوتات متحركة',
    price: 180,
    originalPrice: 200,
    category: 'electronics',
    features: ['هيكل ألومنيوم متين', '4 محركات DC', 'عجلات مطاطية', 'حامل بطارية مدمج'],
    tags: ['robotics', 'chassis', 'motors', 'wheels'],
    image: 'https://images.pexels.com/photos/2599244/pexels-photo-2599244.jpeg?auto=compress&cs=tinysrgb&w=400',
    rating: 4.7,
    reviews: 93,
    inStock: true,
    stockQuantity: 20,
    discount: 10,
    featured: true
  },
  {
    name: 'Solar Panel Kit',
    description: 'مجموعة ألواح شمسية صغيرة مع منظم شحن لمشاريع الطاقة المتجددة',
    price: 150,
    category: 'electronics',
    features: ['لوح شمسي 5W', 'منظم شحن', 'كابلات توصيل', 'دليل مشاريع'],
    tags: ['solar', 'renewable', 'energy', 'power'],
    image: 'https://images.pexels.com/photos/356036/pexels-photo-356036.jpeg?auto=compress&cs=tinysrgb&w=400',
    rating: 4.6,
    reviews: 85,
    inStock: true,
    stockQuantity: 25,
    featured: false
  },
  {
    name: 'Sensor Development Kit',
    description: 'مجموعة شاملة من المستشعرات المختلفة لمشاريع إنترنت الأشياء والتحكم',
    price: 220,
    originalPrice: 250,
    category: 'electronics',
    features: ['15 نوع مستشعر مختلف', 'دليل استخدام', 'أمثلة برمجية', 'صندوق تخزين'],
    tags: ['sensors', 'iot', 'development', 'kit'],
    image: 'https://images.pexels.com/photos/163100/circuit-circuit-board-resistor-computer-163100.jpeg?auto=compress&cs=tinysrgb&w=400',
    rating: 4.8,
    reviews: 102,
    inStock: true,
    stockQuantity: 15,
    discount: 12,
    featured: true
  },
  {
    name: 'Micro:bit Educational Kit',
    description: 'مجموعة تعليمية متكاملة مع لوحة Micro:bit للبرمجة وملحقاتها',
    price: 190,
    category: 'electronics',
    features: ['لوحة Micro:bit', 'ملحقات متنوعة', 'دليل مشاريع', 'كابل USB'],
    tags: ['microbit', 'education', 'programming', 'stem'],
    image: 'https://images.pexels.com/photos/2599244/pexels-photo-2599244.jpeg?auto=compress&cs=tinysrgb&w=400',
    rating: 4.9,
    reviews: 128,
    inStock: true,
    stockQuantity: 30,
    featured: true
  },
  {
    name: 'Drone Building Kit',
    description: 'مجموعة متكاملة لبناء طائرة بدون طيار مع إطار ومحركات ووحدة تحكم',
    price: 450,
    originalPrice: 500,
    category: 'electronics',
    features: ['إطار كربون فايبر', '4 محركات brushless', 'وحدة تحكم طيران', 'جهاز تحكم عن بعد'],
    tags: ['drone', 'quadcopter', 'flying', 'robotics'],
    image: 'https://images.pexels.com/photos/2599244/pexels-photo-2599244.jpeg?auto=compress&cs=tinysrgb&w=400',
    rating: 4.7,
    reviews: 86,
    inStock: true,
    stockQuantity: 10,
    discount: 10,
    featured: true
  },
  {
    name: 'Mechanical Components Set',
    description: 'مجموعة من المكونات الميكانيكية كالتروس والمحاور والبراغي لمشاريع الروبوتات',
    price: 120,
    category: 'materials',
    features: ['تروس بأحجام مختلفة', 'محاور ومثبتات', 'براغي وصواميل', 'قطع ربط متنوعة'],
    tags: ['mechanical', 'gears', 'robotics', 'components'],
    image: 'https://images.pexels.com/photos/6044198/pexels-photo-6044198.jpeg?auto=compress&cs=tinysrgb&w=400',
    rating: 4.5,
    reviews: 74,
    inStock: true,
    stockQuantity: 35,
    featured: false
  },
  {
    name: '3D Printing Filament Pack',
    description: 'مجموعة من خيوط الطباعة ثلاثية الأبعاد PLA بألوان متعددة',
    price: 180,
    category: 'materials',
    features: ['5 لفات بألوان مختلفة', 'قطر 1.75 مم', 'وزن كل لفة 1 كجم', 'جودة عالية'],
    tags: ['3d-printing', 'filament', 'pla', 'materials'],
    image: 'https://images.pexels.com/photos/6044198/pexels-photo-6044198.jpeg?auto=compress&cs=tinysrgb&w=400',
    rating: 4.6,
    reviews: 89,
    inStock: true,
    stockQuantity: 25,
    featured: false
  },
  {
    name: 'Microcontroller Programming Book',
    description: 'كتاب شامل لتعلم برمجة المتحكمات الدقيقة من الأساسيات إلى المشاريع المتقدمة',
    price: 95,
    category: 'books',
    features: ['400 صفحة', 'أمثلة عملية', 'مشاريع تطبيقية', 'رمز مصدري مرفق'],
    tags: ['book', 'programming', 'microcontroller', 'education'],
    image: 'https://images.pexels.com/photos/256431/pexels-photo-256431.jpeg?auto=compress&cs=tinysrgb&w=400',
    rating: 4.8,
    reviews: 112,
    inStock: true,
    stockQuantity: 40,
    featured: false
  },
  {
    name: 'Robotics Projects Handbook',
    description: 'دليل عملي لمشاريع الروبوتات مع تعليمات خطوة بخطوة ونصائح للمبتدئين والمتقدمين',
    price: 85,
    category: 'books',
    features: ['350 صفحة', '20 مشروع كامل', 'رسومات توضيحية', 'نصائح وحلول للمشاكل الشائعة'],
    tags: ['book', 'robotics', 'projects', 'guide'],
    image: 'https://images.pexels.com/photos/256431/pexels-photo-256431.jpeg?auto=compress&cs=tinysrgb&w=400',
    rating: 4.7,
    reviews: 96,
    inStock: true,
    stockQuantity: 45,
    featured: false
  },
  {
    name: 'Electronics Components Encyclopedia',
    description: 'موسوعة شاملة للمكونات الإلكترونية مع شرح مفصل لكل مكون وتطبيقاته',
    price: 120,
    category: 'books',
    features: ['500 صفحة', 'أكثر من 1000 مكون', 'رسومات تفصيلية', 'أمثلة دوائر'],
    tags: ['book', 'electronics', 'components', 'reference'],
    image: 'https://images.pexels.com/photos/256431/pexels-photo-256431.jpeg?auto=compress&cs=tinysrgb&w=400',
    rating: 4.9,
    reviews: 128,
    inStock: true,
    stockQuantity: 30,
    featured: true
  },
  {
    name: 'Raspberry Pi Projects Kit',
    description: 'مجموعة متكاملة من المكونات والملحقات لمشاريع Raspberry Pi مع دليل المشاريع',
    price: 350,
    originalPrice: 400,
    category: 'electronics',
    features: ['Raspberry Pi 4 مدمج', '30 مكون مختلف', 'دليل 15 مشروع', 'صندوق تخزين'],
    tags: ['raspberry-pi', 'kit', 'projects', 'electronics'],
    image: 'https://images.pexels.com/photos/2582937/pexels-photo-2582937.jpeg?auto=compress&cs=tinysrgb&w=400',
    rating: 4.8,
    reviews: 145,
    inStock: true,
    stockQuantity: 15,
    discount: 12,
    featured: true
  },
  {
    name: 'STEM Education Robot Kit',
    description: 'مجموعة تعليمية لبناء وبرمجة روبوت تفاعلي لتعلم مبادئ العلوم والتقنية والهندسة والرياضيات',
    price: 280,
    category: 'electronics',
    features: ['سهل التجميع', 'قابل للبرمجة', 'مستشعرات متعددة', 'دليل تعليمي شامل'],
    tags: ['stem', 'robot', 'education', 'programming'],
    image: 'https://images.pexels.com/photos/2599244/pexels-photo-2599244.jpeg?auto=compress&cs=tinysrgb&w=400',
    rating: 4.9,
    reviews: 156,
    inStock: true,
    stockQuantity: 20,
    featured: true
  },
  {
    name: 'IoT Development Board',
    description: 'لوحة تطوير متخصصة لمشاريع إنترنت الأشياء مع اتصال Wi-Fi وبلوتوث ومستشعرات مدمجة',
    price: 180,
    category: 'electronics',
    features: ['Wi-Fi و Bluetooth مدمجين', 'مستشعرات متعددة', 'استهلاك طاقة منخفض', 'دعم MQTT'],
    tags: ['iot', 'development', 'wifi', 'sensors'],
    image: 'https://images.pexels.com/photos/2582937/pexels-photo-2582937.jpeg?auto=compress&cs=tinysrgb&w=400',
    rating: 4.7,
    reviews: 108,
    inStock: true,
    stockQuantity: 25,
    featured: false
  },
  {
    name: 'Portable Oscilloscope',
    description: 'راسم ذبذبات محمول صغير الحجم لتحليل الإشارات الكهربائية في الميدان',
    price: 420,
    originalPrice: 450,
    category: 'tools',
    features: ['نطاق تردد 50MHz', 'شاشة ملونة 4 بوصة', 'بطارية مدمجة', 'تخزين البيانات'],
    tags: ['oscilloscope', 'portable', 'measurement', 'electronics'],
    image: 'https://images.pexels.com/photos/6044198/pexels-photo-6044198.jpeg?auto=compress&cs=tinysrgb&w=400',
    rating: 4.6,
    reviews: 87,
    inStock: true,
    stockQuantity: 15,
    discount: 6,
    featured: false
  },
  {
    name: 'Electronics Learning Lab',
    description: 'معمل تعليمي متكامل للإلكترونيات مع دوائر وتجارب معدة مسبقاً',
    price: 250,
    category: 'electronics',
    features: ['130 تجربة مختلفة', 'دليل تعليمي', 'مكونات متنوعة', 'لوحة تجارب مدمجة'],
    tags: ['learning', 'electronics', 'lab', 'education'],
    image: 'https://images.pexels.com/photos/163100/circuit-circuit-board-resistor-computer-163100.jpeg?auto=compress&cs=tinysrgb&w=400',
    rating: 4.8,
    reviews: 132,
    inStock: true,
    stockQuantity: 20,
    featured: true
  },
  {
    name: 'Wireless Camera Module',
    description: 'وحدة كاميرا لاسلكية لمشاريع المراقبة والرؤية الحاسوبية',
    price: 130,
    category: 'electronics',
    features: ['دقة 1080p', 'اتصال Wi-Fi', 'رؤية ليلية', 'زاوية رؤية واسعة'],
    tags: ['camera', 'wireless', 'vision', 'surveillance'],
    image: 'https://images.pexels.com/photos/163100/circuit-circuit-board-resistor-computer-163100.jpeg?auto=compress&cs=tinysrgb&w=400',
    rating: 4.5,
    reviews: 94,
    inStock: true,
    stockQuantity: 30,
    featured: false
  },
  {
    name: 'Programmable LED Strip',
    description: 'شريط LED قابل للبرمجة لمشاريع الإضاءة التفاعلية والديكور',
    price: 85,
    category: 'electronics',
    features: ['طول 5 متر', '60 LED لكل متر', 'RGB كامل الألوان', 'تحكم رقمي'],
    tags: ['led', 'strip', 'lighting', 'programmable'],
    image: 'https://images.pexels.com/photos/442150/pexels-photo-442150.jpeg?auto=compress&cs=tinysrgb&w=400',
    rating: 4.6,
    reviews: 118,
    inStock: true,
    stockQuantity: 40,
    featured: false
  },
  {
    name: 'Touchscreen Display Module',
    description: 'شاشة لمس ملونة لواجهات المستخدم التفاعلية في المشاريع الإلكترونية',
    price: 160,
    category: 'electronics',
    features: ['شاشة 7 بوصة', 'دقة 800×480', 'تقنية لمس سعوية', 'واجهة SPI'],
    tags: ['touchscreen', 'display', 'interface', 'lcd'],
    image: 'https://images.pexels.com/photos/442150/pexels-photo-442150.jpeg?auto=compress&cs=tinysrgb&w=400',
    rating: 4.7,
    reviews: 103,
    inStock: true,
    stockQuantity: 25,
    featured: false
  },
  {
    name: 'Precision Tool Set',
    description: 'مجموعة أدوات دقيقة للإلكترونيات والميكانيكا الدقيقة',
    price: 140,
    category: 'tools',
    features: ['45 قطعة مختلفة', 'فولاذ عالي الجودة', 'حقيبة تخزين', 'مقابض مريحة'],
    tags: ['tools', 'precision', 'electronics', 'mechanical'],
    image: 'https://images.pexels.com/photos/6044198/pexels-photo-6044198.jpeg?auto=compress&cs=tinysrgb&w=400',
    rating: 4.6,
    reviews: 97,
    inStock: true,
    stockQuantity: 30,
    featured: false
  }
];

/**
 * Adds store products to the Firestore database, preventing duplicates.
 */
export const addStoreProductsToDatabase = async () => {
  try {
    console.log('Starting to add store products to database...');
    const storeRef = collection(db, 'store_items');
    let addedCount = 0;

    for (const product of storeProducts) {
      // Check if a product with the same name already exists
      const q = query(storeRef, where('name', '==', product.name));
      const snapshot = await getDocs(q);

      if (snapshot.empty) {
        // Product does not exist, add it
        await addDoc(storeRef, {
          name: product.name,
          description: product.description,
          price: product.price,
          original_price: product.originalPrice,
          category: product.category,
          features: product.features,
          tags: product.tags,
          image_url: product.image,
          rating: product.rating,
          reviews_count: product.reviews,
          views_count: 0,
          in_stock: product.inStock,
          stock_quantity: product.stockQuantity,
          discount_percentage: product.discount,
          featured: product.featured,
          created_at: serverTimestamp(),
          updated_at: serverTimestamp()
        });
        addedCount++;
      } else {
        console.log(`Product "${product.name}" already exists, skipping.`);
      }
    }
    
    console.log(`Successfully added ${addedCount} new products to the database!`);
    return true;
  } catch (error) {
    console.error('Error adding store products:', error);
    throw error;
  }
};